version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
  jupyter-pyspark:
    image: quay.io/jupyter/pyspark-notebook:8f03304445ec
    container_name: jupyter-pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work